### ISSUE TITLE
Legge inn støtte for --vars til deployment-cli

### ISSUE THREAD

**Issue by ahusby** [navikt/circleci-nais-orb#6]
Ved deploy til Nais ønsker jeg å kunne angi Kubernetes namespace i tillegg til cluster.

Bakgrunnen er at i mitt prosjekt (Modernisering av folkereigstret i Nav (MFN) ønsker utviklerne å deploye til ulike, selvalgte namespaces for testing av sine feature-brancher, og når vi skal prodsette skal vi deploye først til et staging-miljø (dev-fss:q1), så uten pause til prod (prod-fss:default) og så uten pause til et prodlikt miljø (dev-fss:q0).

Forøvrig tror jeg parameteren "environment" burde hete noe med cluster, f.eks. "k8sCluster", for er det ikke slik at et miljø i Nais-verdenen er identifisert av kombinasjonen av et cluster og et namespace? Det aner meg at forvirringen har oppstått fordi mange pleier å bruke namespacet "default", og det trenger man ikke å angi eksplisitt, og da har man begynt å tenke at cluster er det samme som et miljø.

**Comment by ahusby** [comment]
Hmm, kan jeg få samme effekt av å bruke flere ulike nais.yml filer i prosjektet/applikasjonen min?

**Comment by ahusby** [comment]
Jeg kan kanskje hacke det til med shell-skript, men det føles ikke helt bra, for da er vi på vei vekk fra brukervennlighet og robusthet.
`sed -i -E "s/(^\s*namespace: )(.*)/\1q1/" nais.yaml`

**Comment by Kyrremann** [comment]
Litt usikker på hvor du mener problemet ditt ligger, men, hvis det er `nais.yaml` som er "problemet", så høres det ut som dere burde ta en titt på templating av manifestet deres. Tror vi prøver å pushe på handlebars.js (eller noe i den dur), da det er det som blir brukt med deployment-cli. Kanskje @ambientsound har tips?

**Comment by kimtore** [comment]
Vet at `deployment-cli` har støtte for templating. Legg inn namespace i values-fila. Så må vi få inn et parameter for å aktivere funksjonen. Dette må gjøres i Orb-en.

**Comment by ahusby** [comment]
@ambientsound Ser du endret tittelen på denne issuen, og det får meg til å skjønne at det ikke er en slik løsning jeg ønsker meg (templating), med mindre du ser for deg en måte å bruke dette på som jeg ikke klarer å se for meg.

Jeg opplever det som unaturlig at k8s cluster angis som parameter til deployment-cli, mens k8s namespace angis i nais.yaml via templating-funksjonalliteten. Fra synsvinkelen til meg som bruker av denne løsningen hører de to så tett sammen at de bør oppgis samtidig og på samme måte. Når jeg skal prodsette skal jeg deploye til tre miljøer. Et miljø i Nais-konktekst er en kombinasjon av cluster og namespace. Mitt staging-miljø er dev-fss:q1. Mitt prod-miljø er prod-fss:default. Mitt prodlike miljø er dev-fss:q0. Hver gang jeg skal fyre av en deploy-kommando må jeg oppgi disse to parametrene.

Jeg er klar over at parametrene er forskjellige fra en teknisk synsvinkel; at cluster-navnet er parameter til `kubectl apply`-kommandoen og namespace-navnet er et felt i manifest-filen nais.yaml. Men dette er tekniske detaljer som bør skjules for brukeren, gitt at hensikten her er å lage noe brukervennlig og lettvint.

Dette er vel like mye et innspill til endring av deployment-cli som til orb-en.

**Comment by kimtore** [comment]
@ahusby 

Hvis vi ser for oss som du sier at et miljø er en kombinasjon av cluster og namespace, skal det da være likt for alle, eller blir det opp til hvert enkelt team å sette det opp? Alle bruker "produksjon", men her stopper likheten. Dere bruker "prod-likt" og "staging" (som for meg høres ut som samme ting.) Noen bruker kun "staging", mens andre har mange flere. Hvordan tenkte du generalisere oppsettet?

Når vi her snakker om templating ser jeg for meg følgende løsning:

nais.yaml
```
---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  namespace: {{namespace}}
(...)
```

production.json
```
{
  "namespace": "default"
}
```

prodlike.json
```
{
  "namespace": "q0"
}
```

staging.json
```
{
  "namespace": "q1"
}
```

CircleCI
```
deployment-cli deploy create --resource nais.yaml --cluster prod-fss --vars production.json
deployment-cli deploy create --resource nais.yaml --cluster dev-fss --vars prodlike.json
deployment-cli deploy create --resource nais.yaml --cluster dev-fss --vars staging.json
```

**Comment by ahusby** [comment]
@ambientsound 
Ok, så du ser for deg en egen vars-fil for hvert miljø. Det vil funke. Det blir litt duplisering når den eneste forskjellen er namespace-navnet, men det vil funke. Det skurrer fremdeles på et konseptuelt/logisk nivå, fordi cluster og namespace angis på forskjellige steder på forskjellige måter når de hører tett, tett sammen.

Skjønner ikke helt hva du mener med spørsmålet om det skal være likt for alle. Det _er_ likt for alle allerede, på den måten at alle må angi både cluster og namespace ved hver deploy. "default" er default namespace-navn, og det skjuler litt at det er slik, men det er slik.

Ang. våre miljøer "staging" og "prodlikt": De vil i praksis være like, og like med prod. Dette er et krav jeg har på meg som føles litt tullete, men det er en kamp jeg ikke har giddet å ta.

**Comment by ahusby** [comment]
Hva med at orbens parameter tar son verdi en string som kan være på en av formene "clusternavn" og "clusternavn:namespacenavn", hvor fravær av ":namespacenavn" betyr at man bruker default namespacenavnet "default"? Da blir parameternavnet "environment" riktig, og det vil være symmetrisk med forslaget i https://github.com/navikt/deployment/issues/17#issuecomment-502095230 (visning av namespace i Github Deployments view-et).

**Comment by kimtore** [comment]
> Skjønner ikke helt hva du mener med spørsmålet om det skal være likt for alle. Det _er_ likt for alle allerede, på den måten at alle må angi både cluster og namespace ved hver deploy. "default" er default namespace-navn, og det skjuler litt at det er slik, men det er slik.

De som kun kjører i default-namespacet trenger ikke angi namespace annet enn i nais.yaml, og det trenger ikke templates.

**Comment by ahusby** [comment]
I diskusjon på Slack https://nav-it.slack.com/archives/CL3G3HZ37/p1563957258013100 kom vi fram til at namespace ikke bør brukes til å simulere miljøer. For den som likevel ønsker å gjøre det vil namesapce uansett ikke være tilgjengelig etter den planlagte innføringen av team-namespace ved overgang til public cloud. Det betyr at denne issuen kan lukkes/avvises for min del..

**Comment by KFBI1706** [comment]
Bare for å bygge litt på eksemplet til @ambientsound så vil jeg vise at dette fortsatt er nyttig. Namespaces kan man gjøre mellom den nye `--var`, men ting som ingresser som også er veldig relevant når man skal ha forskjellige miljøer; må man gjøre via templating.

nais.yaml
```
---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  namespace: {{namespace}}
ingresses:
{{#each ingresses}}
- "{{this}}"
{{/each}}
(...)
```
production.json
```
{
  "application_name": "testapp",
  "ingresses": [
    "https://testapp.nais.oera.no",
    "https://testapp.nav.no"
  ]
}
```

q0.json
```
{
  "application_name": "testapp",
  "application_name": "testapp",
  "ingresses": [
    "https://testapp.nais.oera-q.local",
    "https://testapp-q.nav.no"
  ]
}
```
er dette relevant for dere @ahusby ?
