### ISSUE TITLE
Bør docker push være et trinn i deploy-jobben istedenfor build-jobben?

### ISSUE THREAD

**Issue by ahusby** [navikt/circleci-nais-orb#9]
Jeg sitter å prøver å bruke CircleCI med denne orb-en. Jeg ser på eksemplet på bruk av orb-en for scenariet hvor man skal bygge og pushe Docker image uten å deploye til Nais: https://circleci.com/orbs/registry/orb/navikt/nais-deployment#usage-push-docker-image-only

Jeg har ikke behov for et Docker  image før jeg skal deploye applikasjonen til Nais/Kubernetes.  Orb-en legger opp til at push av Docker image til Docker Hub er en del av build-jobben, altså at det skjer hver gang man kompilerer programkoden til applikasjonen og kjører tester. Er ikke det litt urasjonelt, da? Når jeg programmerere pleier jeg å pushe koden til min feature branch i remote Git repo ofte, for å ha backup. Det betyr at det bygges og publiseres mange Docker images (for feature branches) som aldri kommer til å bli brukt. 

Uavhengig av min personlige arbeidsflyt virker det konseptuelt riktigere at `docker push` er en del av deploy-jobben.

**Comment by ahusby** [comment]
Jo mer jeg tenker på dette jo mer mener jeg at orb-en skjuler at det er tre distinkte trinn i denne prosessen: 1) kompilere, kjøre tester og bygge Docker image, 2) laste opp Docker image til Docker Hub eler Github Package Registry, og 3) deploye til Nais/Kubernetes.

Under utvikling, på en feature branch, er det ofte ingen grunn til å laste opp noe Docker image etter kompilering og kjøring av tester. Ved prodsetting i mitt prosjekt ønsker vi å deploye samme Docker image tre ganger: til staging-miljø, til prod og til prodlikt miljø (dette er relatert til issue https://github.com/navikt/circleci-nais-orb/issues/6). Dette betyr at de tre trinnene bør være løsere koblet enn (det ser ut som) de er i orb-en nå.

**Comment by kimtore** [comment]
Enig i at her er det tre trinn, med bygging, push, og deploy.

Med dagens løse kobling kan man deploye docker-containere fra en feature branch i clusteret. Det kan være ønskelig.

Du mener altså vi skal splitte opp bygg og push?

**Comment by ahusby** [comment]
Ja, splitt bygg og docker push. Det børe være lett å bygge applikasjonen (og gjerne Docker imaget, for å verifisere at det funker å bygge det) uten å pushe/publisere Docker imaget.

Ang. feature branch: I mitt prosjekt sin arbeidsflyt skal vi også deploye (et Docker image fra) en feature branch, men det skjer antageligvis sjeldnere enn at at vi bare skal bygge.

**Comment by ahusby** [comment]
Også splitt `docker push` fra deploy. Fordi ved prodsetting ønsker jeg deploye samme Docker image til begge clusterne (dev-fss og prod-fss).
